name: Create ALF File

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-tag: [2021.3.23f1]

    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}

    steps:
    - run: mkdir artifact
    - run: /opt/Unity/Editor/Unity -batchmode -nographics -logFile - -executeMethod UnityEditor.SyncVS.SyncSolution -projectPath ./src -quit || exit 0
    - run: cp ./ artifact
      env:
        UNITY_VERSION: ${{ matrix.unity-tag }}
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.unity-tag }}
        path: artifact
