name: Qodana
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Remove post-checkout hook'
        run: rm -rf .git/hooks/post-checkout
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        with:
          args: --project-dir,./src
          upload-result: false
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ${{ runner.temp }}/qodana/results